### ISSUE TITLE
`codelists` module should handle codlists.txt with`/` at ends of lines

### ISSUE THREAD

**Issue by HelenCEBM** [opensafely-core/opensafely-cli#72] opened 2021-11-17 12:19 UTC
People often incorrectly include forward slashes at the ends of codelists listed in `codelists.txt` (because they copy them from URLs)

e.g. `nhsbsa/icd10-gastro-intestinal-bleed/5d4b7131/`

AFAIK, if you just have a single codelist listed and it has a forward slash, the `codelists update` command fails and the slash must be removed. However, it seems that if you have multiple codelists and some of them have `/` at the end it runs successfully but includes the version number in the filename of the affected codelist `csv`s, which is not the intended/expected behaviour and makes updates more complex to deal with.

e.g. `nhsbsa-icd10-gastro-intestinal-bleed-5d4b7131.csv`

**Comment by Jongmassey** [comment] 2021-11-17 12:53
duplicate of #57

**Closed by Jongmassey** 2021-11-17 12:53 UTC
